In [1]:
import pandas as pd
from os import listdir
from os.path import isfile, join
import numpy as numpy 
from sklearn.feature_extraction.text import TfidfTransformer,CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.cluster import MiniBatchKMeans
import matplotlib.pyplot as plt

In [2]:
print(listdir())

['api.py', 'data_input.csv', 'Dockerfile', 'requirements.txt', 'train.py', 'utils.ipynb']


In [3]:
df=pd.read_csv(input())
df.head()

id                                           abstract
0   0  Turing machines and G\"odel numbers are import...
1   1  RNA-sequencing has revolutionized biomedical r...
2   2  Queuing models provide insight into the tempor...
3   3  In a multiple-object auction, every bidder tri...
4   4  In arXiv:1109.6438v1 [math.AG] we introduced a...

In [4]:
column=input()
df = df.sample(frac=1).reset_index(drop=True)
df_Test=df.iloc[:int(len(df)*0.4)]
df_Train=df.iloc[int(len(df)*0.4):]
scores=[]
best=None
for i in range(8,50):
    pipeline=Pipeline([
        ('vect',CountVectorizer()),
        ('tfidf',TfidfTransformer()),
        ('mbkm',MiniBatchKMeans(n_clusters=i,max_iter=40,batch_size=200,init='k-means++'))
    ])
    pipeline.fit(df_Train[column])
    score=pipeline['mbkm'].score(pipeline['tfidf'].transform(pipeline['vect'].transform((df_Test[column]))))
    print("Score: ",score, "Clusters ",i)
    scores.append(score)
    if(score==min(scores)):
        best=i
plt.scatter(range(1,50),scores)

Score:  -32280.727854536755 Clusters  8
Score:  -32260.562631150187 Clusters  9
Score:  -32272.83928782367 Clusters  10
Score:  -32203.931457945942 Clusters  11
Score:  -32203.601644849812 Clusters  12
Score:  -32186.87320572888 Clusters  13
Score:  -32154.79733208841 Clusters  14
Score:  -32255.062229894993 Clusters  15
Score:  -32116.845490373995 Clusters  16
Score:  -32201.824246271113 Clusters  17
Score:  -32058.67954722667 Clusters  18
Score:  -32213.59154791987 Clusters  19
Score:  -32209.583525172933 Clusters  20
Score:  -32082.866258780225 Clusters  21
Score:  -32215.95201573263 Clusters  22
Score:  -32166.695653512263 Clusters  23
Score:  -32314.825649409206 Clusters  24
Score:  -32081.943370075445 Clusters  25
Score:  -32164.82129132391 Clusters  26
Score:  -32195.647871897094 Clusters  27
Score:  -32043.677371265578 Clusters  28
Score:  -32133.58585250525 Clusters  29
Score:  -32133.66066809429 Clusters  30
Score:  -32162.893975330004 Clusters  31
Score:  -32213.057668794336

ValueError: x and y must be the same size

In [10]:
print("Best: ", min(scores), "Clusters ",best)
pipeline=Pipeline([
    ('vect',CountVectorizer()),
    ('tfidf',TfidfTransformer()),
    ('mbkm',MiniBatchKMeans(n_clusters=best,max_iter=40,batch_size=200,init='k-means++'))
])
pipeline.fit(df[column])
for c in pipeline['mbkm'].cluster_centers_:
    print("------------------------------------------")
    print(c)

Best:  -32314.825649409206 Clusters  24
[0.         0.00016269 0.         ... 0.         0.         0.        ]
[0. 0. 0. ... 0. 0. 0.]
[6.56781393e-05 3.81247957e-04 4.82105528e-06 ... 0.00000000e+00
 0.00000000e+00 0.00000000e+00]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.         0.00092477 0.         ... 0.         0.         0.        ]
[2.13769851e-04 4.40750221e-05 0.00000000e+00 ... 0.00000000e+00
 0.00000000e+00 0.00000000e+00]
[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 6.71684258e-05
 6.71684258e-05 0.00000000e+00]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0.00015039 0.         0.         ... 0.         0.         0.00025319]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[0. 0. 0. ... 0. 0. 0.]
[1.45205070e-05 3.84283902e-04 0.00000000e+00 ... 0.00000000e+00
 0.00000000e+00 0.00000000e+00]
[1.91383475e-05 6.25625378e-04 0.00000000e+0